#!/bin/bash

echo "What is the name of the program?"
read -e PROG_NAME

if [[ ! -d $PROG_NAME ]]; then
	echo "$PROG_NAME directory does not exist. Create it? [y/N]"
	read -e ANSWER
	if [[ $ANSWER == y ]]; then
		mkdir $PROG_NAME
	else
		echo "Cannot find $PROG_NAME directory!"
		exit 1
	fi
fi

FILE=$PROG_NAME/Makefile

if [[ -f $FILE ]]; then
	echo "$FILE already exists. Overwrite it? [y/N]"
	read -e ANSWER
	if [[ $ANSWER == y ]]; then
		rm "$FILE"
	else
		echo "$FILE already exists!"
		exit 1
	fi
fi

echo "What source files are there? (eg one.c two.c three.c)"
read -e SOURCES

echo "include ../common.mk" > $FILE
echo "" >> $FILE
echo "SRC = $SOURCES" >> $FILE
echo "" >> $FILE
echo '%_:' >> $FILE
echo '	$($(addprefix $@, CC)) $($(addprefix $@, FLAGS)) $($(addprefix $@, SRC)) $(SRC) -o $(addsuffix '$PROG_NAME', $@)' >> $FILE
echo "" >> $FILE
echo "clean:" >> $FILE
echo "	rm -f *.o *_$PROG_NAME" >> $FILE
echo "" >> $FILE
echo "# vim: set ts=4 sw=4 noet:" >> $FILE

echo "Success!"

# vim: set ts=4 sw=4 noet:
